--============================
-- Magnitude Analaysis
--============================




-- Find Total customers By Countries

SELECT 
	COUNTRY,
	COUNT(customer_key) AS [total_customers_by_country]
FROM gold.dim_customers
GROUP BY COUNTRY
ORDER BY total_customers_by_country DESC



-- Find total Customers by gender

SELECT 
	gender,
	COUNT(customer_key) AS [TotalCustomersByGender]
FROM gold.dim_customers
GROUP BY gender
ORDER BY [TotalCustomersByGender] DESC

-- Find total product by category

SELECT  
	Category,
	COUNT(Product_name) AS [TotalProduct_ByCategory]
FROM gold.dim_products
GROUP BY category
ORDER BY [TotalProduct_ByCategory] desc


-- Find the average cost in each category

SELECT 
	Category,
	AVG(cost) AS AverageCost
FROM gold.dim_products
GROUP BY category
ORDER BY AverageCost DESC

-- Find the revenue generated for each category



SELECT 
	t1.category,
	SUM(t2.sales_amount) as [Total_revenue]	
FROM gold.dim_products AS t1
INNER JOIN 
gold.fact_sales AS t2
ON t1.product_key = t2.product_key
GROUP BY t1.category
ORDER BY total_revenue DESC


-- What is total revenue generated by each customer

SELECT 
	t1.customer_key,
	t1.customer_number,
	CONCAT(first_name,' ',last_name),
	SUM(sales_amount) AS [total_sales]
FROM gold.dim_customers AS t1
LEFT JOIN
gold.fact_sales AS t2
ON t1.customer_key = t2.customer_key
GROUP BY t1.customer_key,
	     t1.customer_number,
	     CONCAT(first_name,' ',last_name)
ORDER BY total_Sales DESC


-- What is the distribition of sold items across countries


SELECT 
	t1.country,
	SUM(T2.quantity) AS [TotalSoldItems]
FROM gold.dim_customers AS t1
LEFT JOIN
gold.fact_sales AS t2
ON t1.customer_key = t2.customer_key
GROUP BY t1.country
ORDER BY [TotalSoldItems] DESC